on:
  pull_request:
  push:
      branches: gp_kp_release

jobs:
    runners:
      strategy:
        matrix:
          version: ["${{ github.head_ref }}","gg_kg_release"]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: foo
           uses: cdsap/ge-experiment-runner@v1.0.1
           with:
             task: "assembleRelease"
             iterations: 5
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             class: "core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/NewsRepository.kt"
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
    report:
      runs-on: "ubuntu-latest"
      needs: [ runners]
      steps:
         - uses: actions/checkout@v3
         - id: fooa
           uses: cdsap/ge-experiment-report@v.1.1
           with:
             task: "assembleRelease"
             max-builds: 999
             experiment-id: ${{github.run_number}}
             tags: "${{ github.head_ref }}, gg_kg_release"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             gh_token: ${{secrets.GITHUB_TOKEN}}
